export const auctions = [
  {
    account: {
      data: [
        'BbpmVPVZl8szYjWupIOtcT3oltDqZX//NMYBm5F8tT0X8HUBpYOjErGPdkZLWwbj0vxItHkOcW8BqvNbMbOL7L9h+OBmknjMZ+Ft0qX1QL+eB0axNvV37FD35k3nkbjuAQ==',
        'base64',
      ],
      executable: false,
      lamports: 1566000,
      owner: 'auctxRXPeJoc4817jDhf4HbjnhEcr1cCXenosMhK5R8',
      rentEpoch: 186,
    },
    pubkey: '7LQrphNXozbmHvnWjRB8c3L6jPbXTXNc3aYEiDr1rYD4',
  },
];

export const metav1Accounts = [
  {
    account: {
      data: [
        'AQAAAAIzNa/evGoXdrhuto8OaY5qxH9D/70WGQy65QWDnsVVAQAAAAAAAAAAAQEAAAACMzWv3rxqF3a4braPDmmOasR/Q/+9FhkMuuUFg57FVQ==',
        'base64',
      ],
      executable: false,
      lamports: 5616720,
      owner: 'metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s',
      rentEpoch: 185,
    },
    pubkey: 'DAP2Bat7oi4Mn3gTuLHpK23AKQKnqpwdvQwxk1bNYQFJ',
  },
  // {
  //   account: {
  //     data: [
  //       'BGEAE4CrnzaaXLXGFQDpz+jpP0v8rDef8LglVpV5pypK2vBPWXe+stDo/VfYGnUo10Yb2D8UWBvKFNtdGU+Dj4QgAAAATWFya2V0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAAAMgAAABodHRwczovL2Fyd2VhdmUubmV0L0ZlR3VRVk5YMHNpMTRuUm1uTEhtMGtDTzdVVGZyeldtb1ltM2l0YU9TWEUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGQAAQEAAABhABOAq582mly1xhUA6c/o6T9L/Kw3n/C4JVaVeacqSgFkAAEB/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==',
  //       'base64',
  //     ],
  //     executable: false,
  //     lamports: 5616720,
  //     owner: 'metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s',
  //     rentEpoch: 186,
  //   },
  //   pubkey: '4oe3PDtdpW6iSSxt54bS251wKjCBDxc5Nrk9YTztb3d5',
  // },
  // {
  //   account: {
  //     data: [
  //       'BGEAE4CrnzaaXLXGFQDpz+jpP0v8rDef8LglVpV5pypKY+ButMTtKR6N7hF+bO+cJKQP3X1ZIMQj9bH7HxKiDDcgAAAAQUFBQQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAAAMgAAABodHRwczovL2Fyd2VhdmUubmV0L0tkbWIwazExSHQ5NzA4ZTZiWWZKMkEycDZocWtUTlJPaW15VllkWmFtTjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOgDAQEAAABhABOAq582mly1xhUA6c/o6T9L/Kw3n/C4JVaVeacqSgFkAAEB/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==',
  //       'base64',
  //     ],
  //     executable: false,
  //     lamports: 5616720,
  //     owner: 'metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s',
  //     rentEpoch: 185,
  //   },
  //   pubkey: 'EctHi6QWtzgh66BwAvc2CD7tVyoZq62qdDwc8QnAkdi5',
  // },
  // {
  //   account: {
  //     data: [
  //       'BGiKBCF1sqrRPdexEnUOp45lGBsQo9k66xqMrV4jEfdE7/ISSgNqVmwyoE19K95Wr0oSS4CBQoXeWgKITO9YijYgAAAATWluYSBXYWxsZXQAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAAAMgAAABodHRwczovL2Fyd2VhdmUubmV0L0pNdU0wOUhEMzZiV05DQW5ISzY5TXYyV2V2V2w0a1FCemFFSl9SY0VQNncAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOgDAQEAAABhABOAq582mly1xhUA6c/o6T9L/Kw3n/C4JVaVeacqSgFkAAEB/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==',
  //       'base64',
  //     ],
  //     executable: false,
  //     lamports: 5616720,
  //     owner: 'metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s',
  //     rentEpoch: 185,
  //   },
  //   pubkey: 'GnuwXKGpwdwFJHY4sZ7bM5A8M6JjX67E4RHPxuReE6Cn',
  // },
  // {
  //   account: {
  //     data: [
  //       'BGEAE4CrnzaaXLXGFQDpz+jpP0v8rDef8LglVpV5pypKzttuPZJaiYAFgo/MPBQNekO9SsX5RUTCk68zAYQAL9sgAAAAS2l0dHkgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAAAMgAAABodHRwczovL2Fyd2VhdmUubmV0L1Q3OG1heGViRDRRbmtsdGVZdUhlUUt3R0I4QUlvbk9TMko1Z3E0Wl9SSjQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOgDAQEAAABhABOAq582mly1xhUA6c/o6T9L/Kw3n/C4JVaVeacqSgFkAAEB/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==',
  //       'base64',
  //     ],
  //     executable: false,
  //     lamports: 5616720,
  //     owner: 'metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s',
  //     rentEpoch: 186,
  //   },
  //   pubkey: '8kWJAZuCmjeGFNc9MrsYR4tjHuAvspveWoQFAjsVAnqD',
  // },
  // {
  //   account: {
  //     data: [
  //       'BGEAE4CrnzaaXLXGFQDpz+jpP0v8rDef8LglVpV5pypKwo4PPgBj6T6RrzcV80ntNgoST9uId/cXdecwc/ko3/4gAAAAQmVhY2gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAAAMgAAABodHRwczovL2Fyd2VhdmUubmV0L0lPeHNYQnkyQUhSNEc5TG9iOVFyVlFUZExoNXZBNzZhQmNSUVVmRzRPUmsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALgLAQEAAABhABOAq582mly1xhUA6c/o6T9L/Kw3n/C4JVaVeacqSgFkAAEB/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==',
  //       'base64',
  //     ],
  //     executable: false,
  //     lamports: 5616720,
  //     owner: 'metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s',
  //     rentEpoch: 186,
  //   },
  //   pubkey: '2b4ACbcuX8voDxHsp5fMyoa81Bf45o1nthXfDriDDBGi',
  // },
];

export const metaplexId = [
  {
    account: {
      data: [
        'AwAIr6m/CoSZ7/WxDMfdJDvgFGdG2/mWVZ2RgsFdvBj2Vw26HDQad3Ne0mDDJLa++rsJ9PU0BzIvMawcKdTp0a8xC3BlsePRfEU4nVJ/awTDzVi4bHMaoP21SbbRvAP4KUYG3fbh12Whk9nL4UbO63msHLSF7V9bN5E6jPWFfv8AqQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=',
        'base64',
      ],
      lamports: 2491680,
      owner: 'p1exdMJcjVao65QdewkaZRUnU6VPSXhus9n2GzWfh98',
      executable: false,
      rentEpoch: 186,
    },
    pubkey: '2pW8qCf5P7zncTSgVH6aPdMSAvHk7iaG3ZHGfeF6dMUv',
  },
  {
    account: {
      data: [
        'BGEAE4CrnzaaXLXGFQDpz+jpP0v8rDef8LglVpV5pypKAQAAAAAAAAAAAAA=',
        'base64',
      ],
      lamports: 1197120,
      owner: 'p1exdMJcjVao65QdewkaZRUnU6VPSXhus9n2GzWfh98',
      executable: false,
      rentEpoch: 186,
    },
    pubkey: '3bFeTtbfn6Xig6aZU3FTTXCKpnU1wEGYB2bKtxrhMBeE',
  },
];
